// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/home/data/repositories/home_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i8;
import 'package:zalando_clone_app/features/home/data/datasources/home_remote_data_source.dart'
    as _i4;
import 'package:zalando_clone_app/features/home/data/models/component_model.dart'
    as _i2;
import 'package:zalando_clone_app/features/home/data/models/page_model.dart'
    as _i6;
import 'package:zalando_clone_app/features/product/domain/entities/product.dart'
    as _i9;
import 'package:zalando_clone_app/features/product/domain/entities/product_category.dart'
    as _i11;
import 'package:zalando_clone_app/features/product/domain/entities/product_list_response.dart'
    as _i10;
import 'package:zalando_clone_app/features/product/domain/repositories/product_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePageComponentsModel_0 extends _i1.SmartFake
    implements _i2.PageComponentsModel {
  _FakePageComponentsModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i4.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.PageModel>> getPages(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #getPages,
          [userId],
        ),
        returnValue: _i5.Future<List<_i6.PageModel>>.value(<_i6.PageModel>[]),
      ) as _i5.Future<List<_i6.PageModel>>);

  @override
  _i5.Future<_i2.PageComponentsModel> getPageComponents(
    int? componentId,
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPageComponents,
          [
            componentId,
            page,
            pageSize,
          ],
        ),
        returnValue: _i5.Future<_i2.PageComponentsModel>.value(
            _FakePageComponentsModel_0(
          this,
          Invocation.method(
            #getPageComponents,
            [
              componentId,
              page,
              pageSize,
            ],
          ),
        )),
      ) as _i5.Future<_i2.PageComponentsModel>);

  @override
  _i5.Future<List<String>> getWelcomeTexts() => (super.noSuchMethod(
        Invocation.method(
          #getWelcomeTexts,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i7.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i8.Failure, _i9.Product>> getProductById({
    required int? productId,
    required String? type,
    int? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [],
          {
            #productId: productId,
            #type: type,
            #templateId: templateId,
          },
        ),
        returnValue: _i5.Future<_i3.Either<_i8.Failure, _i9.Product>>.value(
            _FakeEither_1<_i8.Failure, _i9.Product>(
          this,
          Invocation.method(
            #getProductById,
            [],
            {
              #productId: productId,
              #type: type,
              #templateId: templateId,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i8.Failure, _i9.Product>>);

  @override
  _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>> getProductList({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductList,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>>.value(
                _FakeEither_1<_i8.Failure, _i10.ProductListResponse>(
          this,
          Invocation.method(
            #getProductList,
            [],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>>);

  @override
  _i5.Future<
      _i3.Either<_i8.Failure, _i10.ProductListResponse>> getProductsByCategory({
    required List<int>? categoryIds,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [],
          {
            #categoryIds: categoryIds,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>>.value(
                _FakeEither_1<_i8.Failure, _i10.ProductListResponse>(
          this,
          Invocation.method(
            #getProductsByCategory,
            [],
            {
              #categoryIds: categoryIds,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>>);

  @override
  _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>> searchProducts({
    required String? query,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [],
          {
            #query: query,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>>.value(
                _FakeEither_1<_i8.Failure, _i10.ProductListResponse>(
          this,
          Invocation.method(
            #searchProducts,
            [],
            {
              #query: query,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i8.Failure, _i10.ProductListResponse>>);

  @override
  _i5.Future<_i3.Either<_i8.Failure, List<_i11.ProductCategory>>>
      getRootCategories({int? maxDepth = 1}) => (super.noSuchMethod(
            Invocation.method(
              #getRootCategories,
              [],
              {#maxDepth: maxDepth},
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i8.Failure, List<_i11.ProductCategory>>>.value(
                _FakeEither_1<_i8.Failure, List<_i11.ProductCategory>>(
              this,
              Invocation.method(
                #getRootCategories,
                [],
                {#maxDepth: maxDepth},
              ),
            )),
          ) as _i5.Future<_i3.Either<_i8.Failure, List<_i11.ProductCategory>>>);

  @override
  _i5.Future<_i3.Either<_i8.Failure, List<_i11.ProductCategory>>>
      getCategoriesByParentId({
    required int? parentId,
    int? maxDepth = 1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getCategoriesByParentId,
              [],
              {
                #parentId: parentId,
                #maxDepth: maxDepth,
              },
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i8.Failure, List<_i11.ProductCategory>>>.value(
                _FakeEither_1<_i8.Failure, List<_i11.ProductCategory>>(
              this,
              Invocation.method(
                #getCategoriesByParentId,
                [],
                {
                  #parentId: parentId,
                  #maxDepth: maxDepth,
                },
              ),
            )),
          ) as _i5.Future<_i3.Either<_i8.Failure, List<_i11.ProductCategory>>>);

  @override
  _i5.Future<_i3.Either<_i8.Failure, List<_i11.ProductCategory>>>
      getAllCategories({
    int? maxDepth = 1,
    int? limit = 20,
    int? offset = 0,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAllCategories,
              [],
              {
                #maxDepth: maxDepth,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i8.Failure, List<_i11.ProductCategory>>>.value(
                _FakeEither_1<_i8.Failure, List<_i11.ProductCategory>>(
              this,
              Invocation.method(
                #getAllCategories,
                [],
                {
                  #maxDepth: maxDepth,
                  #limit: limit,
                  #offset: offset,
                },
              ),
            )),
          ) as _i5.Future<_i3.Either<_i8.Failure, List<_i11.ProductCategory>>>);
}
