// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/search/domain/usecases/get_search_categories_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/features/search/domain/entities/search_category.dart'
    as _i5;
import 'package:zalando_clone_app/features/search/domain/entities/search_subcategory.dart'
    as _i7;
import 'package:zalando_clone_app/features/search/domain/entities/search_tab.dart'
    as _i6;
import 'package:zalando_clone_app/features/search/domain/entities/subcategory_details.dart'
    as _i2;
import 'package:zalando_clone_app/features/search/domain/repositories/search_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubcategoryDetails_0 extends _i1.SmartFake
    implements _i2.SubcategoryDetails {
  _FakeSubcategoryDetails_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i3.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.SearchCategory>> getSearchCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.SearchCategory>>.value(<_i5.SearchCategory>[]),
      ) as _i4.Future<List<_i5.SearchCategory>>);

  @override
  _i4.Future<List<_i6.SearchTab>> getSearchTabs() => (super.noSuchMethod(
        Invocation.method(
          #getSearchTabs,
          [],
        ),
        returnValue: _i4.Future<List<_i6.SearchTab>>.value(<_i6.SearchTab>[]),
      ) as _i4.Future<List<_i6.SearchTab>>);

  @override
  _i4.Future<List<_i7.SearchSubcategory>> getSubcategories(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubcategories,
          [categoryId],
        ),
        returnValue: _i4.Future<List<_i7.SearchSubcategory>>.value(
            <_i7.SearchSubcategory>[]),
      ) as _i4.Future<List<_i7.SearchSubcategory>>);

  @override
  _i4.Future<List<_i7.SearchSubcategory>> getNestedSubcategories(
          String? subcategoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNestedSubcategories,
          [subcategoryId],
        ),
        returnValue: _i4.Future<List<_i7.SearchSubcategory>>.value(
            <_i7.SearchSubcategory>[]),
      ) as _i4.Future<List<_i7.SearchSubcategory>>);

  @override
  _i4.Future<_i2.SubcategoryDetails> getSubcategoryDetails(
          String? subcategoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubcategoryDetails,
          [subcategoryId],
        ),
        returnValue:
            _i4.Future<_i2.SubcategoryDetails>.value(_FakeSubcategoryDetails_0(
          this,
          Invocation.method(
            #getSubcategoryDetails,
            [subcategoryId],
          ),
        )),
      ) as _i4.Future<_i2.SubcategoryDetails>);

  @override
  _i4.Future<void> updateSelectedTab(String? tabId) => (super.noSuchMethod(
        Invocation.method(
          #updateSelectedTab,
          [tabId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.SearchCategory>> searchCategories(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCategories,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i5.SearchCategory>>.value(<_i5.SearchCategory>[]),
      ) as _i4.Future<List<_i5.SearchCategory>>);
}
