// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/home/domain/usecases/get_pages_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i5;
import 'package:zalando_clone_app/features/home/domain/entities/component.dart'
    as _i9;
import 'package:zalando_clone_app/features/home/domain/entities/page.dart'
    as _i8;
import 'package:zalando_clone_app/features/home/domain/entities/product.dart'
    as _i6;
import 'package:zalando_clone_app/features/home/domain/repositories/home_repository.dart'
    as _i3;
import 'package:zalando_clone_app/features/product/domain/entities/product_category.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>
      getFeaturedProducts() => (super.noSuchMethod(
            Invocation.method(
              #getFeaturedProducts,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Product>>(
              this,
              Invocation.method(
                #getFeaturedProducts,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getProductsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [category],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getProductsByCategory,
            [category],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ProductCategory>>>
      getRootCategories() => (super.noSuchMethod(
            Invocation.method(
              #getRootCategories,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i7.ProductCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.ProductCategory>>(
              this,
              Invocation.method(
                #getRootCategories,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ProductCategory>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> searchProducts(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #searchProducts,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getProductsByBrand(
          String? brand) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByBrand,
          [brand],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getProductsByBrand,
            [brand],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Page>>> getPages(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPages,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i8.Page>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.Page>>(
          this,
          Invocation.method(
            #getPages,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Page>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.PageComponents>> getPageComponents(
    int? componentId,
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPageComponents,
          [
            componentId,
            page,
            pageSize,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i9.PageComponents>>.value(
                _FakeEither_0<_i5.Failure, _i9.PageComponents>(
          this,
          Invocation.method(
            #getPageComponents,
            [
              componentId,
              page,
              pageSize,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.PageComponents>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getWelcomeTexts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWelcomeTexts,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getWelcomeTexts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);
}
