// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/product/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/features/product/data/datasources/product_remote_data_source.dart'
    as _i4;
import 'package:zalando_clone_app/features/product/data/models/product_category_model.dart'
    as _i6;
import 'package:zalando_clone_app/features/product/data/models/product_list_response_model.dart'
    as _i3;
import 'package:zalando_clone_app/features/product/data/models/product_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductListResponseModel_1 extends _i1.SmartFake
    implements _i3.ProductListResponseModel {
  _FakeProductListResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i4.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProductModel> getProductById({
    required int? productId,
    required String? type,
    int? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [],
          {
            #productId: productId,
            #type: type,
            #templateId: templateId,
          },
        ),
        returnValue: _i5.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #getProductById,
            [],
            {
              #productId: productId,
              #type: type,
              #templateId: templateId,
            },
          ),
        )),
      ) as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<_i3.ProductListResponseModel> getProductList({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductList,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<_i3.ProductListResponseModel>.value(
            _FakeProductListResponseModel_1(
          this,
          Invocation.method(
            #getProductList,
            [],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i3.ProductListResponseModel>);

  @override
  _i5.Future<_i3.ProductListResponseModel> getProductsByCategory({
    required List<int>? categoryIds,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [],
          {
            #categoryIds: categoryIds,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<_i3.ProductListResponseModel>.value(
            _FakeProductListResponseModel_1(
          this,
          Invocation.method(
            #getProductsByCategory,
            [],
            {
              #categoryIds: categoryIds,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i3.ProductListResponseModel>);

  @override
  _i5.Future<_i3.ProductListResponseModel> searchProducts({
    required String? query,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [],
          {
            #query: query,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<_i3.ProductListResponseModel>.value(
            _FakeProductListResponseModel_1(
          this,
          Invocation.method(
            #searchProducts,
            [],
            {
              #query: query,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i5.Future<_i3.ProductListResponseModel>);

  @override
  _i5.Future<List<_i6.ProductCategoryModel>> getRootCategories(
          {int? maxDepth = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRootCategories,
          [],
          {#maxDepth: maxDepth},
        ),
        returnValue: _i5.Future<List<_i6.ProductCategoryModel>>.value(
            <_i6.ProductCategoryModel>[]),
      ) as _i5.Future<List<_i6.ProductCategoryModel>>);

  @override
  _i5.Future<List<_i6.ProductCategoryModel>> getCategoriesByParentId({
    required int? parentId,
    int? maxDepth = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesByParentId,
          [],
          {
            #parentId: parentId,
            #maxDepth: maxDepth,
          },
        ),
        returnValue: _i5.Future<List<_i6.ProductCategoryModel>>.value(
            <_i6.ProductCategoryModel>[]),
      ) as _i5.Future<List<_i6.ProductCategoryModel>>);

  @override
  _i5.Future<List<_i6.ProductCategoryModel>> getAllCategories({
    int? maxDepth = 1,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
          {
            #maxDepth: maxDepth,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i6.ProductCategoryModel>>.value(
            <_i6.ProductCategoryModel>[]),
      ) as _i5.Future<List<_i6.ProductCategoryModel>>);
}
