// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/home/presentation/bloc/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i7;
import 'package:zalando_clone_app/features/home/domain/entities/component.dart'
    as _i12;
import 'package:zalando_clone_app/features/home/domain/entities/page.dart'
    as _i10;
import 'package:zalando_clone_app/features/home/domain/entities/product.dart'
    as _i8;
import 'package:zalando_clone_app/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:zalando_clone_app/features/home/domain/usecases/get_featured_products_usecase.dart'
    as _i5;
import 'package:zalando_clone_app/features/home/domain/usecases/get_page_components_usecase.dart'
    as _i11;
import 'package:zalando_clone_app/features/home/domain/usecases/get_pages_usecase.dart'
    as _i9;
import 'package:zalando_clone_app/features/product/domain/entities/product_category.dart'
    as _i14;
import 'package:zalando_clone_app/features/product/domain/repositories/product_repository.dart'
    as _i4;
import 'package:zalando_clone_app/features/product/domain/usecases/get_root_categories.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRepository_2 extends _i1.SmartFake
    implements _i4.ProductRepository {
  _FakeProductRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFeaturedProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFeaturedProductsUseCase extends _i1.Mock
    implements _i5.GetFeaturedProductsUseCase {
  MockGetFeaturedProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.Product>>> call(
          _i5.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i8.Product>>>.value(
                _FakeEither_1<_i7.Failure, List<_i8.Product>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i8.Product>>>);
}

/// A class which mocks [GetPagesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPagesUseCase extends _i1.Mock implements _i9.GetPagesUseCase {
  MockGetPagesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i10.Page>>> call(
          _i9.GetPagesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, List<_i10.Page>>>.value(
            _FakeEither_1<_i7.Failure, List<_i10.Page>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i10.Page>>>);
}

/// A class which mocks [GetPageComponentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPageComponentsUseCase extends _i1.Mock
    implements _i11.GetPageComponentsUseCase {
  MockGetPageComponentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i12.PageComponents>> call(
          _i11.GetPageComponentsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, _i12.PageComponents>>.value(
                _FakeEither_1<_i7.Failure, _i12.PageComponents>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i12.PageComponents>>);
}

/// A class which mocks [GetRootCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRootCategoriesUseCase extends _i1.Mock
    implements _i13.GetRootCategoriesUseCase {
  MockGetRootCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ProductRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i14.ProductCategory>>> call(
          _i13.GetRootCategoriesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6
            .Future<_i3.Either<_i7.Failure, List<_i14.ProductCategory>>>.value(
            _FakeEither_1<_i7.Failure, List<_i14.ProductCategory>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i14.ProductCategory>>>);
}
