// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/addresses/presentation/bloc/address_bloc_country_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i9;
import 'package:zalando_clone_app/features/addresses/domain/entities/address.dart'
    as _i3;
import 'package:zalando_clone_app/features/addresses/domain/repositories/address_repository.dart'
    as _i2;
import 'package:zalando_clone_app/features/addresses/domain/usecases/add_address.dart'
    as _i7;
import 'package:zalando_clone_app/features/addresses/domain/usecases/delete_address.dart'
    as _i10;
import 'package:zalando_clone_app/features/addresses/domain/usecases/get_addresses.dart'
    as _i5;
import 'package:zalando_clone_app/features/addresses/domain/usecases/get_countries.dart'
    as _i12;
import 'package:zalando_clone_app/features/addresses/domain/usecases/get_states.dart'
    as _i13;
import 'package:zalando_clone_app/features/addresses/domain/usecases/set_default_address.dart'
    as _i11;
import 'package:zalando_clone_app/features/addresses/domain/usecases/update_address.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddressRepository_0 extends _i1.SmartFake
    implements _i2.AddressRepository {
  _FakeAddressRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddress_1 extends _i1.SmartFake implements _i3.Address {
  _FakeAddress_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAddresses].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAddresses extends _i1.Mock implements _i5.GetAddresses {
  MockGetAddresses() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddressRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AddressRepository);

  @override
  _i6.Future<List<_i3.Address>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Address>>.value(<_i3.Address>[]),
      ) as _i6.Future<List<_i3.Address>>);
}

/// A class which mocks [AddAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddAddress extends _i1.Mock implements _i7.AddAddress {
  MockAddAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddressRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AddressRepository);

  @override
  _i6.Future<_i3.Address> call(_i3.Address? address) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [address],
        ),
        returnValue: _i6.Future<_i3.Address>.value(_FakeAddress_1(
          this,
          Invocation.method(
            #call,
            [address],
          ),
        )),
      ) as _i6.Future<_i3.Address>);
}

/// A class which mocks [UpdateAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAddress extends _i1.Mock implements _i8.UpdateAddress {
  MockUpdateAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddressRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AddressRepository);

  @override
  _i6.Future<_i4.Either<_i9.Failure, void>> call(_i3.Address? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, void>>.value(
            _FakeEither_2<_i9.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, void>>);
}

/// A class which mocks [DeleteAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAddress extends _i1.Mock implements _i10.DeleteAddress {
  MockDeleteAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddressRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AddressRepository);

  @override
  _i6.Future<bool> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [SetDefaultAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetDefaultAddress extends _i1.Mock implements _i11.SetDefaultAddress {
  MockSetDefaultAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddressRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AddressRepository);

  @override
  _i6.Future<_i3.Address> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i6.Future<_i3.Address>.value(_FakeAddress_1(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.Address>);
}

/// A class which mocks [GetCountries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountries extends _i1.Mock implements _i12.GetCountries {
  MockGetCountries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeAddressRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.AddressRepository);

  @override
  _i6.Future<List<Map<String, dynamic>>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [GetStates].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStates extends _i1.Mock implements _i13.GetStates {
  MockGetStates() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeAddressRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i2.AddressRepository);

  @override
  _i6.Future<List<Map<String, dynamic>>> call(int? countryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [countryId],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);
}
