// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/favorites/data/repositories/favorites_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/network/network_info.dart' as _i6;
import 'package:zalando_clone_app/features/favorites/data/datasources/favorites_local_data_source.dart'
    as _i2;
import 'package:zalando_clone_app/features/favorites/data/datasources/favorites_remote_data_source.dart'
    as _i5;
import 'package:zalando_clone_app/features/favorites/data/models/favorite_product_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoritesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesLocalDataSource extends _i1.Mock
    implements _i2.FavoritesLocalDataSource {
  MockFavoritesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FavoriteProductModel>> getFavorites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i3.Future<List<_i4.FavoriteProductModel>>.value(
            <_i4.FavoriteProductModel>[]),
      ) as _i3.Future<List<_i4.FavoriteProductModel>>);

  @override
  _i3.Future<void> addToFavorites(_i4.FavoriteProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [product],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromFavorites(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [productId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorite(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [productId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> clearFavorites() => (super.noSuchMethod(
        Invocation.method(
          #clearFavorites,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [FavoritesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRemoteDataSource extends _i1.Mock
    implements _i5.FavoritesRemoteDataSource {
  MockFavoritesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FavoriteProductModel>> getWishlist() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWishlist,
          [],
        ),
        returnValue: _i3.Future<List<_i4.FavoriteProductModel>>.value(
            <_i4.FavoriteProductModel>[]),
      ) as _i3.Future<List<_i4.FavoriteProductModel>>);

  @override
  _i3.Future<void> addToWishlist(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #addToWishlist,
          [productId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromWishlist(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromWishlist,
          [productId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
