// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/filters/presentation/bloc/filter_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i5;
import 'package:zalando_clone_app/features/filters/domain/entities/filter_attribute.dart'
    as _i8;
import 'package:zalando_clone_app/features/filters/domain/entities/filter_brand.dart'
    as _i7;
import 'package:zalando_clone_app/features/filters/domain/entities/filter_category.dart'
    as _i6;
import 'package:zalando_clone_app/features/filters/domain/entities/filter_criteria.dart'
    as _i10;
import 'package:zalando_clone_app/features/filters/domain/entities/filter_options.dart'
    as _i9;
import 'package:zalando_clone_app/features/filters/domain/repositories/filter_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FilterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterRepository extends _i1.Mock implements _i3.FilterRepository {
  MockFilterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.FilterCategory>>> getCategories({
    int? page = 1,
    int? limit = 6,
    int? parentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
          {
            #page: page,
            #limit: limit,
            #parentId: parentId,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.FilterCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.FilterCategory>>(
          this,
          Invocation.method(
            #getCategories,
            [],
            {
              #page: page,
              #limit: limit,
              #parentId: parentId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.FilterCategory>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.FilterBrand>>> getBrands({
    int? page = 1,
    int? limit = 7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrands,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.FilterBrand>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.FilterBrand>>(
          this,
          Invocation.method(
            #getBrands,
            [],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.FilterBrand>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.FilterAttribute>>> getAttributes({
    int? page = 1,
    int? limit = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttributes,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i8.FilterAttribute>>>.value(
            _FakeEither_0<_i5.Failure, List<_i8.FilterAttribute>>(
          this,
          Invocation.method(
            #getAttributes,
            [],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.FilterAttribute>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.FilterOptions>> getFilterOptions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilterOptions,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i9.FilterOptions>>.value(
                _FakeEither_0<_i5.Failure, _i9.FilterOptions>(
          this,
          Invocation.method(
            #getFilterOptions,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.FilterOptions>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> filterProducts(
          _i10.FilterCriteria? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterProducts,
          [criteria],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #filterProducts,
            [criteria],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.FilterOptions>> getAvailableFilters({
    String? category,
    String? brand,
    String? query,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableFilters,
          [],
          {
            #category: category,
            #brand: brand,
            #query: query,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i9.FilterOptions>>.value(
                _FakeEither_0<_i5.Failure, _i9.FilterOptions>(
          this,
          Invocation.method(
            #getAvailableFilters,
            [],
            {
              #category: category,
              #brand: brand,
              #query: query,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.FilterOptions>>);
}
