// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/favorites/presentation/bloc/favorites_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i6;
import 'package:zalando_clone_app/features/favorites/domain/entities/favorite_product.dart'
    as _i7;
import 'package:zalando_clone_app/features/favorites/domain/repositories/favorites_repository.dart'
    as _i2;
import 'package:zalando_clone_app/features/favorites/domain/usecases/add_to_favorites_usecase.dart'
    as _i8;
import 'package:zalando_clone_app/features/favorites/domain/usecases/check_favorite_status_usecase.dart'
    as _i10;
import 'package:zalando_clone_app/features/favorites/domain/usecases/clear_favorites_usecase.dart'
    as _i11;
import 'package:zalando_clone_app/features/favorites/domain/usecases/get_favorites_usecase.dart'
    as _i4;
import 'package:zalando_clone_app/features/favorites/domain/usecases/remove_from_favorites_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoritesRepository_0 extends _i1.SmartFake
    implements _i2.FavoritesRepository {
  _FakeFavoritesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoritesUseCase extends _i1.Mock
    implements _i4.GetFavoritesUseCase {
  MockGetFavoritesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFavoritesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.FavoriteProduct>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, List<_i7.FavoriteProduct>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.FavoriteProduct>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.FavoriteProduct>>>);
}

/// A class which mocks [AddToFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddToFavoritesUseCase extends _i1.Mock
    implements _i8.AddToFavoritesUseCase {
  MockAddToFavoritesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFavoritesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i7.FavoriteProduct? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [product],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [product],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [RemoveFromFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFromFavoritesUseCase extends _i1.Mock
    implements _i9.RemoveFromFavoritesUseCase {
  MockRemoveFromFavoritesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFavoritesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [productId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [productId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [CheckFavoriteStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckFavoriteStatusUseCase extends _i1.Mock
    implements _i10.CheckFavoriteStatusUseCase {
  MockCheckFavoriteStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFavoritesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [productId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [productId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [ClearFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearFavoritesUseCase extends _i1.Mock
    implements _i11.ClearFavoritesUseCase {
  MockClearFavoritesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFavoritesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
