// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/search/presentation/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i7;
import 'package:zalando_clone_app/core/usecases/usecase.dart' as _i9;
import 'package:zalando_clone_app/features/search/domain/entities/search_category.dart'
    as _i8;
import 'package:zalando_clone_app/features/search/domain/entities/search_subcategory.dart'
    as _i13;
import 'package:zalando_clone_app/features/search/domain/entities/search_tab.dart'
    as _i11;
import 'package:zalando_clone_app/features/search/domain/entities/subcategory_details.dart'
    as _i4;
import 'package:zalando_clone_app/features/search/domain/repositories/search_repository.dart'
    as _i2;
import 'package:zalando_clone_app/features/search/domain/usecases/get_search_categories.dart'
    as _i5;
import 'package:zalando_clone_app/features/search/domain/usecases/get_search_tabs.dart'
    as _i10;
import 'package:zalando_clone_app/features/search/domain/usecases/get_subcategories.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchRepository_0 extends _i1.SmartFake
    implements _i2.SearchRepository {
  _FakeSearchRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubcategoryDetails_2 extends _i1.SmartFake
    implements _i4.SubcategoryDetails {
  _FakeSubcategoryDetails_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSearchCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSearchCategories extends _i1.Mock
    implements _i5.GetSearchCategories {
  MockGetSearchCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SearchRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.SearchCategory>>> call(
          _i9.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i8.SearchCategory>>>.value(
                _FakeEither_1<_i7.Failure, List<_i8.SearchCategory>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i8.SearchCategory>>>);
}

/// A class which mocks [GetSearchTabs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSearchTabs extends _i1.Mock implements _i10.GetSearchTabs {
  MockGetSearchTabs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SearchRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i11.SearchTab>>> call(
          _i9.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i11.SearchTab>>>.value(
                _FakeEither_1<_i7.Failure, List<_i11.SearchTab>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i11.SearchTab>>>);
}

/// A class which mocks [GetSubcategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSubcategories extends _i1.Mock implements _i12.GetSubcategories {
  MockGetSubcategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSearchRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.SearchRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i13.SearchSubcategory>>> call(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i6.Future<
                _i3.Either<_i7.Failure, List<_i13.SearchSubcategory>>>.value(
            _FakeEither_1<_i7.Failure, List<_i13.SearchSubcategory>>(
          this,
          Invocation.method(
            #call,
            [categoryId],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i13.SearchSubcategory>>>);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i2.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i8.SearchCategory>> getSearchCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchCategories,
          [],
        ),
        returnValue:
            _i6.Future<List<_i8.SearchCategory>>.value(<_i8.SearchCategory>[]),
      ) as _i6.Future<List<_i8.SearchCategory>>);

  @override
  _i6.Future<List<_i11.SearchTab>> getSearchTabs() => (super.noSuchMethod(
        Invocation.method(
          #getSearchTabs,
          [],
        ),
        returnValue: _i6.Future<List<_i11.SearchTab>>.value(<_i11.SearchTab>[]),
      ) as _i6.Future<List<_i11.SearchTab>>);

  @override
  _i6.Future<List<_i13.SearchSubcategory>> getSubcategories(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubcategories,
          [categoryId],
        ),
        returnValue: _i6.Future<List<_i13.SearchSubcategory>>.value(
            <_i13.SearchSubcategory>[]),
      ) as _i6.Future<List<_i13.SearchSubcategory>>);

  @override
  _i6.Future<List<_i13.SearchSubcategory>> getNestedSubcategories(
          String? subcategoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNestedSubcategories,
          [subcategoryId],
        ),
        returnValue: _i6.Future<List<_i13.SearchSubcategory>>.value(
            <_i13.SearchSubcategory>[]),
      ) as _i6.Future<List<_i13.SearchSubcategory>>);

  @override
  _i6.Future<_i4.SubcategoryDetails> getSubcategoryDetails(
          String? subcategoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubcategoryDetails,
          [subcategoryId],
        ),
        returnValue:
            _i6.Future<_i4.SubcategoryDetails>.value(_FakeSubcategoryDetails_2(
          this,
          Invocation.method(
            #getSubcategoryDetails,
            [subcategoryId],
          ),
        )),
      ) as _i6.Future<_i4.SubcategoryDetails>);

  @override
  _i6.Future<void> updateSelectedTab(String? tabId) => (super.noSuchMethod(
        Invocation.method(
          #updateSelectedTab,
          [tabId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.SearchCategory>> searchCategories(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCategories,
          [query],
        ),
        returnValue:
            _i6.Future<List<_i8.SearchCategory>>.value(<_i8.SearchCategory>[]),
      ) as _i6.Future<List<_i8.SearchCategory>>);
}
