// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/product/presentation/bloc/product_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i6;
import 'package:zalando_clone_app/features/product/domain/entities/product.dart'
    as _i7;
import 'package:zalando_clone_app/features/product/domain/entities/product_category.dart'
    as _i13;
import 'package:zalando_clone_app/features/product/domain/entities/product_list_response.dart'
    as _i9;
import 'package:zalando_clone_app/features/product/domain/repositories/product_repository.dart'
    as _i2;
import 'package:zalando_clone_app/features/product/domain/usecases/get_all_categories.dart'
    as _i15;
import 'package:zalando_clone_app/features/product/domain/usecases/get_categories_by_parent_id.dart'
    as _i14;
import 'package:zalando_clone_app/features/product/domain/usecases/get_product_by_id.dart'
    as _i4;
import 'package:zalando_clone_app/features/product/domain/usecases/get_product_list.dart'
    as _i8;
import 'package:zalando_clone_app/features/product/domain/usecases/get_products_by_category.dart'
    as _i10;
import 'package:zalando_clone_app/features/product/domain/usecases/get_root_categories.dart'
    as _i12;
import 'package:zalando_clone_app/features/product/domain/usecases/search_products.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductRepository_0 extends _i1.SmartFake
    implements _i2.ProductRepository {
  _FakeProductRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetProductById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductById extends _i1.Mock implements _i4.GetProductById {
  MockGetProductById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Product>> call(
          _i4.GetProductByIdParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>.value(
            _FakeEither_1<_i6.Failure, _i7.Product>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Product>>);
}

/// A class which mocks [GetProductList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductList extends _i1.Mock implements _i8.GetProductList {
  MockGetProductList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>> call(
          _i8.GetProductListParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>>.value(
                _FakeEither_1<_i6.Failure, _i9.ProductListResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>>);
}

/// A class which mocks [GetProductsByCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsByCategory extends _i1.Mock
    implements _i10.GetProductsByCategory {
  MockGetProductsByCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>> call(
          _i10.GetProductsByCategoryParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>>.value(
                _FakeEither_1<_i6.Failure, _i9.ProductListResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>>);
}

/// A class which mocks [SearchProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProducts extends _i1.Mock implements _i11.SearchProducts {
  MockSearchProducts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>> call(
          _i11.SearchProductsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>>.value(
                _FakeEither_1<_i6.Failure, _i9.ProductListResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.ProductListResponse>>);
}

/// A class which mocks [GetRootCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRootCategoriesUseCase extends _i1.Mock
    implements _i12.GetRootCategoriesUseCase {
  MockGetRootCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>> call(
          _i12.GetRootCategoriesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>>.value(
            _FakeEither_1<_i6.Failure, List<_i13.ProductCategory>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>>);
}

/// A class which mocks [GetCategoriesByParentIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesByParentIdUseCase extends _i1.Mock
    implements _i14.GetCategoriesByParentIdUseCase {
  MockGetCategoriesByParentIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>> call(
          _i14.GetCategoriesByParentIdParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>>.value(
            _FakeEither_1<_i6.Failure, List<_i13.ProductCategory>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>>);
}

/// A class which mocks [GetAllCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesUseCase extends _i1.Mock
    implements _i15.GetAllCategoriesUseCase {
  MockGetAllCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ProductRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>> call(
          _i15.GetAllCategoriesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>>.value(
            _FakeEither_1<_i6.Failure, List<_i13.ProductCategory>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i13.ProductCategory>>>);
}
