// Mocks generated by Mockito 5.4.5 from annotations
// in zalando_clone_app/test/features/product/domain/usecases/get_product_by_id_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:zalando_clone_app/core/errors/failures.dart' as _i5;
import 'package:zalando_clone_app/features/product/domain/entities/product.dart'
    as _i6;
import 'package:zalando_clone_app/features/product/domain/entities/product_category.dart'
    as _i8;
import 'package:zalando_clone_app/features/product/domain/entities/product_list_response.dart'
    as _i7;
import 'package:zalando_clone_app/features/product/domain/repositories/product_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i3.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Product>> getProductById({
    required int? productId,
    required String? type,
    int? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [],
          {
            #productId: productId,
            #type: type,
            #templateId: templateId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>.value(
            _FakeEither_0<_i5.Failure, _i6.Product>(
          this,
          Invocation.method(
            #getProductById,
            [],
            {
              #productId: productId,
              #type: type,
              #templateId: templateId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>> getProductList({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductList,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>>.value(
                _FakeEither_0<_i5.Failure, _i7.ProductListResponse>(
          this,
          Invocation.method(
            #getProductList,
            [],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i7.ProductListResponse>> getProductsByCategory({
    required List<int>? categoryIds,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [],
          {
            #categoryIds: categoryIds,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>>.value(
                _FakeEither_0<_i5.Failure, _i7.ProductListResponse>(
          this,
          Invocation.method(
            #getProductsByCategory,
            [],
            {
              #categoryIds: categoryIds,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>> searchProducts({
    required String? query,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [],
          {
            #query: query,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>>.value(
                _FakeEither_0<_i5.Failure, _i7.ProductListResponse>(
          this,
          Invocation.method(
            #searchProducts,
            [],
            {
              #query: query,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ProductListResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductCategory>>>
      getRootCategories({int? maxDepth = 1}) => (super.noSuchMethod(
            Invocation.method(
              #getRootCategories,
              [],
              {#maxDepth: maxDepth},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i8.ProductCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.ProductCategory>>(
              this,
              Invocation.method(
                #getRootCategories,
                [],
                {#maxDepth: maxDepth},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductCategory>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductCategory>>>
      getCategoriesByParentId({
    required int? parentId,
    int? maxDepth = 1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getCategoriesByParentId,
              [],
              {
                #parentId: parentId,
                #maxDepth: maxDepth,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i8.ProductCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.ProductCategory>>(
              this,
              Invocation.method(
                #getCategoriesByParentId,
                [],
                {
                  #parentId: parentId,
                  #maxDepth: maxDepth,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductCategory>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductCategory>>>
      getAllCategories({
    int? maxDepth = 1,
    int? limit = 20,
    int? offset = 0,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAllCategories,
              [],
              {
                #maxDepth: maxDepth,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i8.ProductCategory>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.ProductCategory>>(
              this,
              Invocation.method(
                #getAllCategories,
                [],
                {
                  #maxDepth: maxDepth,
                  #limit: limit,
                  #offset: offset,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductCategory>>>);
}
